logging:
  level:
    org:
    springframework:
    security: DEBUG

server:
  port: 8080
  servlet:
    context-path: /supperspeed
  access-token: 6e9bcb840461718912b38556131f9b28f50fd2d3

google:
  api:
    key: AIzaSyBZ_SIP2pulfzYNyz_-2KY5mI32Y_RvM5M
  geocode:
    url: https://maps.googleapis.com/maps/api/geocode/json

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supper_speed
    username: postgres
    password: Cypriankos2134
    hikari:
      idle-timeout: 10000
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    enabled: true
    oauth2:
      client:
        registration:
          imgur:
            client-id: 6bdd28332e8362b
            client-secret: 51ed1c38718827328b239a8a76bf94d09d1c416a
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/imgur
        provider:
          imgur:
            token-uri: https://api.imgur.com/oauth2/token
            authorization-uri: https://api.imgur.com/oauth2/authorize