logging:
  level:
    org:
    springframework:
    security: DEBUG

server:
  port: 8080
  servlet:
    context-path: /supperspeed
  access-token: 6e9bcb840461718912b38556131f9b28f50fd2d3

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supper_speed
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html